// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_handler from "./routes/api/handler.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Journal from "./islands/Journal.tsx";
import * as $JournalBox from "./islands/JournalBox.tsx";
import * as $JournalList from "./islands/JournalList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/handler.ts": $api_handler,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Journal.tsx": $Journal,
    "./islands/JournalBox.tsx": $JournalBox,
    "./islands/JournalList.tsx": $JournalList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
